service: covidnearme
custom:
  pythonRequirements:
    usePipenv: true

package:
  exclude:
    - "frontend/**"

provider:
  name: aws
  runtime: python3.7

  stage: prod
  region: eu-west-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource:
        - { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "CovidData" } ] ]  }
        - { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "CovidData" }, "/*" ] ]  }

functions:
  covid:
    handler: src/get_covid_data.handler
    events:
      - http:
          path: covid
          method: get
          cors:
            origin: '*'
          request:
            parameters:
              querystrings:
                url: true
  covid_cases_and_death:
    handler: src/get_covid_cases_and_deaths_data.handler
    events:
      - http:
          path: covid/all
          method: get
          cors:
            origin: '*'
          request:
            parameters:
              querystrings:
                url: true
  district:
    handler: src/get_districts.handler
    events:
      - http:
          path: districts
          method: get
          cors:
            origin: '*'
  data_loader:
    handler: src/data_loader.handler
    timeout: 400
    environment:
      GOOGLE_PLACES_API_KEY: $GOOGLE_PLACES_API_KEY
    events:
      - schedule: rate(12 hours)

resources:
  Resources:
    CovidData:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: covidnearme.xyz
    CovidNearMeZone:
      Type: AWS::Route53::HostedZone
      Properties:
        Name: covidnearme.xyz
    CovidNearMeRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref 'CovidNearMeZone'
        Name: covidnearme.xyz
        ResourceRecords:
          - 104.198.14.52
        TTL: '900'
        Type: A
    CovidNearMeRecordWWW:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref 'CovidNearMeZone'
        Name: www.covidnearme.xyz
        ResourceRecords:
          - 104.198.14.52
        TTL: '900'
        Type: A
    CovidNearMeRecordAPI:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref 'CovidNearMeZone'
        Name: api.covidnearme.xyz
        ResourceRecords:
          - pn6ecfl253.execute-api.eu-west-2.amazonaws.com
        TTL: '900'
        Type: CNAME
plugins:
  - serverless-python-requirements
