on:
  push:
    branches: master

name: Serverless deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: serverless deploy
      uses: benjefferies/github-action@master
      with:
        args: -c "cat serverless.yml | envsubst '$GOOGLE_PLACES_API_KEY' | sponge serverless.yml && serverless plugin install --name serverless-python-requirements && serverless deploy --verbose"
        entrypoint: /bin/bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GOOGLE_PLACES_API_KEY: ${{ secrets.GOOGLE_PLACES_API_KEY }}
