on:
  push:
    branches: master

name: Serverless deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: serverless deploy
      uses: serverless/github-action@e17abe72d4969e86cb53576ade34e95c40362f0e
      with:
        args: -c "serverless plugin install --name serverless-python-requirements && serverless deploy --verbose"
        entrypoint: /bin/bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
